### ISSUE TITLE
inplace transformations

### ISSUE THREAD

**Issue by ktye** [scientificgo/fft#1]
It looks like the functions radix3, radix5, ... always make a copy of the input array.
What about an in-place interface?
The copy for the current case could be moved to fft.go, and another function e.g. FftOverwrite would call the underlying functions with the original slice.

**Comment by ijxy** [comment]
@ktye The approach you mention could work, and I appreciate that for very large data doing the transform in-place could make an appreciable difference in the speed and especially in memory-usage (see below for radix-3 example, out-of-place is ~16.5% slower across the bechmarks).

API-wise, I'd probably lean towards something like 
```Go
Fft(x []complex128, opts *Options) []complex128
```
where options is a new type, e.g. 
```Go
type Options struct {
  Inverse bool
  Overwrite bool
}
```
instead of exposing a new function. This seems tidy to me and would allow further options to be added later without a breaking change. Breaking changes are not really a problem for now, but it would be nice to release a v1 in the new year.

My main worry is that it will only be possible to offer the 'Overwrite' option for radix-3,5,6,7 without making more effort. This is because the Stockham algorithm for radix-2 cases is an out-of-place algorithm by design and the Bluestein algorithm for prime (and radix > 7) cases depends on it too. The solution to this may be as simple as having separate functions for doing in-place radix-2 transforms, and in-place "Bluestein" transforms, but I don't have any data on how that would change the performance.

I'd be interested to hear your thoughts on the proposed API change and concerns about the radix-2 case.

Benchmarks
---

For reference, I've just benchmarked using in-place for radix 3:

### Out-of-place
```
$ go test -v -run=None -bench=/3-
goos: linux
goarch: amd64
pkg: scientificgo.org/fft
BenchmarkFft/3-3-4 	20000000	        88.6 ns/op
BenchmarkFft/3-9-4 	10000000	       211 ns/op
BenchmarkFft/3-27-4         	 3000000	       533 ns/op
BenchmarkFft/3-81-4         	 1000000	      1556 ns/op
BenchmarkFft/3-243-4        	  300000	      5068 ns/op
BenchmarkFft/3-729-4        	  100000	     16638 ns/op
BenchmarkFft/3-2187-4       	   30000	     56374 ns/op
BenchmarkFft/3-6561-4       	   10000	    188949 ns/op
BenchmarkFft/3-19683-4      	    2000	    659194 ns/op
BenchmarkIffti/3-3-4        	20000000	        94.2 ns/op
BenchmarkIffti/3-9-4        	10000000	       222 ns/op
BenchmarkIffti/3-27-4       	 3000000	       586 ns/op
BenchmarkIffti/3-81-4       	 1000000	      1834 ns/op
BenchmarkIffti/3-243-4      	  200000	      6345 ns/op
BenchmarkIffti/3-729-4      	  100000	     20842 ns/op
BenchmarkIffti/3-2187-4     	   20000	     68994 ns/op
BenchmarkIffti/3-6561-4     	   10000	    233556 ns/op
BenchmarkIffti/3-19683-4    	    2000	    816706 ns/op
PASS
ok  	scientificgo.org/fft	35.305s
```

### In-place
```Go
  case 3:
    res = x
    radix3(res, s)
```
```
$ go test -v -run=None -bench=/3-
goos: linux
goarch: amd64
pkg: scientificgo.org/fft
BenchmarkFft/3-3-4 	20000000	        62.8 ns/op
BenchmarkFft/3-9-4 	10000000	       162 ns/op
BenchmarkFft/3-27-4         	 3000000	       435 ns/op
BenchmarkFft/3-81-4         	 1000000	      1328 ns/op
BenchmarkFft/3-243-4        	  300000	      4410 ns/op
BenchmarkFft/3-729-4        	  100000	     14963 ns/op
BenchmarkFft/3-2187-4       	   30000	     51369 ns/op
BenchmarkFft/3-6561-4       	   10000	    172447 ns/op
BenchmarkFft/3-19683-4      	    2000	    594855 ns/op
BenchmarkIffti/3-3-4        	20000000	        67.5 ns/op
BenchmarkIffti/3-9-4        	10000000	       175 ns/op
BenchmarkIffti/3-27-4       	 3000000	       487 ns/op
BenchmarkIffti/3-81-4       	 1000000	      1506 ns/op
BenchmarkIffti/3-243-4      	  300000	      4974 ns/op
BenchmarkIffti/3-729-4      	  100000	     16641 ns/op
BenchmarkIffti/3-2187-4     	   30000	     56048 ns/op
BenchmarkIffti/3-6561-4     	   10000	    187544 ns/op
BenchmarkIffti/3-19683-4    	    2000	    644071 ns/op
PASS
ok  	scientificgo.org/fft	29.978s
```

**Comment by ktye** [comment]
The api you propose looks good.
I didn't realize, that stockham uses a temporary array.
I have an implementation for powers of two with an in-place transform in `github.com/ktye/fft`.

The real benefit is, if you have to apply the same transform over and over again. So if you have to do setup work, maybe it would be good to separate the call to an initialization and the transform.
An example application is a spectrogram which applies the transform with a fixed windows size many times.

**Comment by ijxy** [comment]
@ktye I would like to measure how much of a difference it makes to have initialize/transform separated before diving too much into implementation details. I will investigate at the weekend when I have time.

That said, these seem to be the options:
1. (Your suggestion) split up `Fft(x, ...)` into `Fft.Init(len(x))` and `Fft.Transform(x, ...)`

2. Cache the twiddle factor components (i.e., sin & cos values) in unexported variables at the package 
  level; this could enable the same performance boost with the single-call design, but is probably less 
  flexible.
   ```Go
   // Cache twiddle factor components to save recomputation for repeated calls.
   var wsin, wcos []float64
   var lastn int
   ```

3. Keep the single call and use the previously discussed Options type. Adding another field, we could
   use something like 
   ```Go
   type Options struct {
     Inverse bool
     Overwrite bool
     // Optional twiddle factors to be used. Calculated if not provided.
     Twiddles []complex128
   }
   ```
   and have logic to use the twiddle factors if they are provided, and to calculate/save them if 
   not. The usage is then very close to your proposal, but makes the initialization step an 
   optional optimisation for the user depending on their need. For example:
   ```Go
   // Single-use call.
   res := Fft(x, nil)

   // Multiple-use calls.
   opts := &Options{Twiddles: []complex128{}}
   resx := Fft(x, opts)
   resy := Fft(y, opts)
   resxx := Fft(resx, opts)
   // and so on, provided x, y have the same length.
   ```

**Comment by ijxy** [comment]
For the sake of completeness, it's also worth pointing out that if I get around to implementing 2/3/N-dimensional transforms then the performance differences will become increasingly significant. So this is certainly something I'm giving serious thought to.

**Comment by ijxy** [comment]
## Some more data, this time for radix2.

---
### Stockham auto-sort, out-of-place
```
$ go test -run=None -bench=Fft/2- -benchtime=2s
goos: linux
goarch: amd64
pkg: scientificgo.org/fft
BenchmarkFft/2-2-4         	30000000	        84.8 ns/op
BenchmarkFft/2-4-4         	20000000	       127 ns/op
BenchmarkFft/2-8-4         	20000000	       208 ns/op
BenchmarkFft/2-16-4        	10000000	       343 ns/op
BenchmarkFft/2-32-4        	 5000000	       604 ns/op
BenchmarkFft/2-64-4        	 3000000	      1153 ns/op
BenchmarkFft/2-128-4       	 1000000	      2348 ns/op
BenchmarkFft/2-256-4       	  500000	      5033 ns/op
BenchmarkFft/2-512-4       	  300000	     11816 ns/op
BenchmarkFft/2-1024-4      	  100000	     24312 ns/op
BenchmarkFft/2-2048-4      	   50000	     52156 ns/op
BenchmarkFft/2-4096-4      	   30000	    111349 ns/op
BenchmarkFft/2-8192-4      	   10000	    244016 ns/op
BenchmarkFft/2-16384-4     	    5000	    533908 ns/op
PASS
ok  	scientificgo.org/fft	45.856s
```

### Cooley-Tukey, out-of-place
```
$ go test -run=None -bench=Fft/2- -benchtime=2s
goos: linux
goarch: amd64
pkg: scientificgo.org/fft
BenchmarkFft/2-2-4         	50000000	        62.8 ns/op
BenchmarkFft/2-4-4         	30000000	       100 ns/op
BenchmarkFft/2-8-4         	20000000	       165 ns/op
BenchmarkFft/2-16-4        	10000000	       295 ns/op
BenchmarkFft/2-32-4        	 5000000	       517 ns/op
BenchmarkFft/2-64-4        	 3000000	       991 ns/op
BenchmarkFft/2-128-4       	 1000000	      2021 ns/op
BenchmarkFft/2-256-4       	 1000000	      4195 ns/op
BenchmarkFft/2-512-4       	  300000	      8759 ns/op
BenchmarkFft/2-1024-4      	  200000	     20220 ns/op
BenchmarkFft/2-2048-4      	  100000	     46921 ns/op
BenchmarkFft/2-4096-4      	   20000	    128884 ns/op
BenchmarkFft/2-8192-4      	   10000	    317571 ns/op
BenchmarkFft/2-16384-4     	    5000	    778702 ns/op
PASS
ok  	scientificgo.org/fft	49.664s
```

### Cooley-Tukey, in-place
```
$ go test -run=None -bench=Fft/2- -benchtime=2s
goos: linux
goarch: amd64
pkg: scientificgo.org/fft
BenchmarkFft/2-2-4         	100000000	        35.2 ns/op
BenchmarkFft/2-4-4         	50000000	        71.6 ns/op
BenchmarkFft/2-8-4         	20000000	       127 ns/op
BenchmarkFft/2-16-4        	20000000	       234 ns/op
BenchmarkFft/2-32-4        	10000000	       419 ns/op
BenchmarkFft/2-64-4        	 3000000	       807 ns/op
BenchmarkFft/2-128-4       	 2000000	      1619 ns/op
BenchmarkFft/2-256-4       	 1000000	      3402 ns/op
BenchmarkFft/2-512-4       	  500000	      7238 ns/op
BenchmarkFft/2-1024-4      	  200000	     15922 ns/op
BenchmarkFft/2-2048-4      	  100000	     36976 ns/op
BenchmarkFft/2-4096-4      	   30000	    109362 ns/op
BenchmarkFft/2-8192-4      	   10000	    279550 ns/op
BenchmarkFft/2-16384-4     	    3000	    721020 ns/op
PASS
ok  	scientificgo.org/fft	51.539s
```

**Comment by ktye** [comment]
What does this compare?
Do you allocate a slice before each transform?
Is the benchmark code in the repository?

**Comment by ijxy** [comment]
@ktye It is a comparison of the existing stockham implementation for radix2, against a radix2 Cooley-Tukey implementation (essentially the same code as radix3.go, radix5.go, etc., but slightly simplified to account for the additional symmetries of the radix2 case) with out-of-place (i.e. allocate/copy before transform) and in-place (no allocate/copy before transform).

I haven't pushed to the new repository because at this stage I'be been investigating. To be clear, I've been investigating:

1. **In-place vs Out-of-place**
   - When is `in-place Cooley-Tukey` faster than `out-of-place Cooley-Tukey` algorithm?
   -  When is `in-place Cooley-Tukey` faster than `out-of-place Stockcham` for radix 2 cases?

2. **Passing vs recalculating twiddle factors**
   - When is `passing a slice` of values faster than `calculating` those values?

*NB: `Cooley-Tukey` here refers to the decimation in time (DIT) type.*

So far, I can confidently make the following claims (per my hardware):

1. **In-place vs out-of-place**
   - `In-place Cooley-Tukey` is always faster than `out-of-place Cooley-Tukey`
   - `In-place Cooley-Tukey` is faster than `out-of-place Stockham` for sizes up to 2048; they are approximately the same for 4096; `out-of-place Stockham` appears to be faster for sizes 8192 and above.

2. **Passing vs recalculating twiddle factors**
   - `Passing` is faster but the %-difference decreases the larger the size. I've tested this on radix3 only so far (see below). I've tested this by adjusting ```radix3``` to accept an `Options` paramater that contains the slice of twiddle factors, and then uses a switch condition to decide whether to calculate them or use the passed slice based on the number of elements in the slice. Again, this is not in the github repository yet and won't be until it becomes clear that it's worth the extra code complexity.
---

### Passing twiddle factors
```
$ go test -run=None -bench=Fft/3- -benchtime=2s
goos: linux
goarch: amd64
pkg: scientificgo.org/fft
BenchmarkFft/3-3-4         	50000000	        67.6 ns/op
BenchmarkFft/3-9-4         	20000000	       157 ns/op
BenchmarkFft/3-27-4        	10000000	       439 ns/op
BenchmarkFft/3-81-4        	 2000000	      1413 ns/op
BenchmarkFft/3-243-4       	  500000	      4866 ns/op
BenchmarkFft/3-729-4       	  200000	     16338 ns/op
BenchmarkFft/3-2187-4      	   50000	     55517 ns/op
BenchmarkFft/3-6561-4      	   20000	    197371 ns/op
BenchmarkFft/3-19683-4     	    5000	    757504 ns/op
PASS
ok  	scientificgo.org/fft	34.888s
```

### Calculating twiddle factors
```
$ go test -run=None -bench=Fft/3- -benchtime=2s
goos: linux
goarch: amd64
pkg: scientificgo.org/fft
BenchmarkFft/3-3-4         	30000000	       111 ns/op
BenchmarkFft/3-9-4         	20000000	       239 ns/op
BenchmarkFft/3-27-4        	 5000000	       582 ns/op
BenchmarkFft/3-81-4        	 2000000	      1671 ns/op
BenchmarkFft/3-243-4       	  500000	      5408 ns/op
BenchmarkFft/3-729-4       	  200000	     17677 ns/op
BenchmarkFft/3-2187-4      	   50000	     62437 ns/op
BenchmarkFft/3-6561-4      	   10000	    230645 ns/op
BenchmarkFft/3-19683-4     	    3000	    792147 ns/op
PASS
ok  	scientificgo.org/fft	32.043s
```
